apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-node-test
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-node-test
    spec:
      containers:
        - name: simple-node-test
          image: registry.dop.clsaa.com/zfl/simple-node-test:<BUILD_TAG>
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 3000
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node-test
  namespace: default
  labels:
    app: simple-node-test
spec:
  ports:
    - port: 15000
      protocol: TCP
      targetPort: 3000
  selector:
    app: simple-node-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-node-test
  namespace: default
spec:
  rules:
    - host: open.dop.clsaa.com
      http:
        paths:
          - backend:
              serviceName: simple-node-test
              servicePort: 15000
